import type { AnalysisInput, DetectiveReport } from '@/types';

export async function analyzeObservation(input: AnalysisInput): Promise<DetectiveReport> {
  const apiUrl = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/analyze-observation`;
  const headers = {
    Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,
    'Content-Type': 'application/json',
  };

  const response = await fetch(apiUrl, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      image: input.image,
      country: input.country,
      city: input.city,
      environment: input.environment,
    }),
  });

  if (!response.ok) {
    const errorBody = await response.json().catch(() => ({}));
    if (response.status === 429 && !errorBody.error) {
      throw new Error('Gemini free-tier rate limit reached. Wait a moment and try again.');
    }
    throw new Error(errorBody.error || `Analysis failed (${response.status})`);
  }

  const data = await response.json();

  if (!data || !Array.isArray(data.observed) || typeof data.possiblePattern !== 'string') {
    throw new Error('Received an invalid response from the AI analysis service.');
  }

  return {
    observed: data.observed,
    possiblePattern: data.possiblePattern,
    priority: data.priority,
    confidence: data.confidence,
    investigateNext: data.investigateNext,
    isSample: false,
  };
}

export const REAL_DISCLAIMER =
  'This analysis was generated by an AI vision model examining the submitted photograph. It describes only what the AI identified in the image and does not constitute an environmental finding. Human verification is required.';
